baseURL = "https://xvx.cz/"
languageCode = "en-US"
title = "XvX.cz Site"
theme = "bootstrap-bp-hugo-startpage"
copyright = "Petr Ruzicka"
enableRobotsTXT = true
pygmentsCodeFences = true
canonifyurls = true

[params]
  description = "XvX.cz Site"
  # images = ["logo.jpg"]
  startPageColumns = false
  welcomeText = "XvX.cz Site"
  showGoogleSearch = false
